name: Create EC2 User and SSH Key

on:
  workflow_dispatch:
    inputs:
      username:
        description: "Linux username to create on EC2"
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  create-user-on-ec2:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::776705051324:role/github-action-role
        aws-region: ${{ env.AWS_REGION }}

    - name: Generate SSH key pair
      id: ssh-keygen
      run: |
        USERNAME="${{ github.event.inputs.username }}"
        ssh-keygen -t rsa -b 2048 -f "$USERNAME" -N ""
        echo "USERNAME=$USERNAME" >> $GITHUB_ENV
        # Save keys as base64 strings to env for safe usage
        echo "PRIVATE_KEY=$(base64 -w 0 $USERNAME)" >> $GITHUB_ENV
        echo "PUBLIC_KEY=$(base64 -w 0 $USERNAME.pub)" >> $GITHUB_ENV
        echo "KEY_FILE=$USERNAME" >> $GITHUB_ENV

    - name: Store keys in AWS Secrets Manager
      run: |
        SECRET_NAME="test"

        # Create secret if it doesn't exist (ignore error if exists)
        aws secretsmanager create-secret --name "$SECRET_NAME" --secret-string '{}' 2>/dev/null || echo "Secret already exists."

        # Put the latest keys into the secret
        aws secretsmanager put-secret-value \
          --secret-id "$SECRET_NAME" \
          --secret-string "{\"private_key\": \"${PRIVATE_KEY}\", \"public_key\": \"${PUBLIC_KEY}\"}" \
          --region $AWS_REGION

    - name: Find EC2 Instance ID
      id: find-ec2
      run: |
        INSTANCE_ID=$(aws ec2 describe-instances \
          --filters "Name=tag:Name,Values=my-ec2-tag" "Name=instance-state-name,Values=running" \
          --query "Reservations[0].Instances[0].InstanceId" --output text \
          --region $AWS_REGION)
        echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV

    - name: Create user and setup SSH access via SSM
      run: |
        USERNAME="${USERNAME}"
        PUBLIC_KEY_CONTENT=$(echo "${PUBLIC_KEY}" | base64 -d)

        aws ssm send-command \
          --instance-ids "${INSTANCE_ID}" \
          --document-name "AWS-RunShellScript" \
          --comment "Create user and add SSH key" \
          --parameters commands="[
            \"set -e\",
            \"sudo useradd -m -s /bin/bash $USERNAME || true\",
            \"sudo passwd -l $USERNAME || true\",
            \"sudo mkdir -p /home/$USERNAME/.ssh\",
            \"echo $PUBLIC_KEY_CONTENT | sudo tee /home/$USERNAME/.ssh/authorized_keys\",
            \"sudo chown -R $USERNAME:$USERNAME /home/$USERNAME/.ssh\",
            \"sudo chmod 700 /home/$USERNAME/.ssh\",
            \"sudo chmod 600 /home/$USERNAME/.ssh/authorized_keys\",
            \"sudo touch /home/$USERNAME/.hushlogin\",
            \"sudo chown $USERNAME:$USERNAME /home/$USERNAME/.hushlogin\"
          ]" \
          --region $AWS_REGION \
          --output text

    - name: Upload private key for download
      uses: actions/upload-artifact@v4
      with:
        name: ec2-private-key-${{ env.USERNAME }}
        path: ${{ env.KEY_FILE }}
